https://www.kaggle.com/uciml/breast-cancer-wisconsin-data

Documentação: https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html#sklearn.tree.DecisionTreeClassifier

## Importing Data

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv(r'C:\Users\rodri\GitHub\My_Projects\1 Aulas Data Science\Data Sets/breast-cancer-wisconsin-data.zip')

In [3]:
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

## Data Cleaning & EDA

In [4]:
df['diagnosis'].value_counts()

B    357
M    212
Name: diagnosis, dtype: int64

In [5]:
d={'M':1,'B':0}
df['diagnosis'] = df['diagnosis'].map(d)
df['diagnosis'].value_counts()

0    357
1    212
Name: diagnosis, dtype: int64

## Train Test Split

In [6]:
from sklearn.model_selection import train_test_split

features = df.drop(['id', 'diagnosis', 'Unnamed: 32'], axis=1)
targets = df['diagnosis']

X_train, X_test, y_train, y_test = train_test_split(features, targets, test_size=0.20, stratify=targets,random_state=1)

## Lista de modelos para treinar

In [7]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier as KNN
from sklearn.metrics import accuracy_score

# Instantiate lr
lr = LogisticRegression(random_state=42, solver='newton-cg')

# Instantiate knn
knn = KNN(n_neighbors=15)

# Instantiate dt
dt = DecisionTreeClassifier(random_state=42)

# Define the list classifiers
classifiers = [('Logistic Regression', lr), ('K Nearest Neighbours', knn), ('Classification Tree', dt)]

In [8]:
# Iterate over the pre-defined list of classifiers
for clf_name, clf in classifiers:    
  
    # Fit clf to the training set
    clf.fit(X_train, y_train)    
  
    # Predict y_pred
    y_pred = clf.predict(X_test)
    
    # Calculate accuracy
    accuracy = accuracy_score(y_test, y_pred)
  
    # Evaluate clf's accuracy on the test set
    print('{:s} : {:.2f} %'.format(clf_name, accuracy*100))

Logistic Regression : 94.74 %
K Nearest Neighbours : 95.61 %
Classification Tree : 92.11 %


In [9]:
# Import VotingClassifier from sklearn.ensemble
from sklearn.ensemble import VotingClassifier

# Instantiate a VotingClassifier vc 
vc = VotingClassifier(estimators=classifiers)     

# Fit vc to the training set
vc.fit(X_train, y_train)   

# Evaluate the test set predictions
y_pred = vc.predict(X_test)

# Calculate accuracy score
accuracy = accuracy_score(y_test, y_pred)
print('Voting Classifier: {:.2f} %'.format(accuracy*100))

Voting Classifier: 97.37 %


## Aplicação simples do modelo na prática:

In [10]:
novo_paciente = [[1.095e+01, 2.135e+01, 7.190e+01, 3.711e+02, 1.227e-01, 1.218e-01,
       1.044e-01, 5.669e-02, 1.895e-01, 6.870e-02, 2.366e-01, 1.428e+00,
       1.822e+00, 1.697e+01, 8.064e-03, 1.764e-02, 2.595e-02, 1.037e-02,
       1.357e-02, 3.040e-03, 1.284e+01, 3.534e+01, 8.722e+01, 5.140e+02,
       1.909e-01, 2.698e-01, 4.023e-01, 1.424e-01, 2.964e-01, 9.606e-02]]

In [11]:
vc.predict(novo_paciente)

array([0], dtype=int64)

In [12]:
novo_paciente = [[1.377e+01, 2.229e+01, 9.063e+01, 5.889e+02, 1.200e-01, 1.267e-01,
       1.385e-01, 6.526e-02, 1.834e-01, 6.877e-02, 6.191e-01, 2.112e+00,
       4.906e+00, 4.970e+01, 1.380e-02, 3.348e-02, 4.665e-02, 2.060e-02,
       2.689e-02, 4.306e-03, 1.639e+01, 3.401e+01, 1.116e+02, 8.069e+02,
       1.737e-01, 3.122e-01, 3.809e-01, 1.673e-01, 3.080e-01, 9.333e-02]]

In [13]:
vc.predict(novo_paciente)

array([1], dtype=int64)

In [16]:
lista_novos_pacientes

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
186       18.310         18.58          118.60     1041.0          0.08588   
384       13.280         13.72           85.79      541.8          0.08363   
429       12.720         17.67           80.98      501.3          0.07896   
467        9.668         18.10           61.06      286.3          0.08311   
540       11.540         14.44           74.65      402.9          0.09984   
471       12.040         28.14           76.85      449.9          0.08752   
35        16.740         21.59          110.10      869.5          0.09610   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
186           0.08468         0.08169             0.058140         0.1621   
384           0.08575         0.05077             0.028640         0.1617   
429           0.04522         0.01402             0.018350         0.1459   
467           0.05428         0.01479             0.005769         0.1680   
540           0.11200         0.06737             0.025940         0.1818   
471           0.06000         0.02367             0.023770         0.1854   
35            0.13360         0.13480             0.060180         0.1896   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
186                 0.05425  ...         21.31          26.36   
384                 0.05594  ...         14.24          17.37   
429                 0.05544  ...         13.82          20.96   
467                 0.06412  ...         11.15          24.62   
540                 0.06782  ...         12.26          19.68   
471                 0.05698  ...         13.60          33.33   
35                  0.05656  ...         20.01          29.02   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
186           139.20      1410.0            0.1234            0.24450   
384            96.59       623.7            0.1166            0.26850   
429            88.87       586.8            0.1068            0.09605   
467            71.11       380.2            0.1388            0.12550   
540            78.78       457.8            0.1345            0.21180   
471            87.24       567.6            0.1041            0.09726   
35            133.50      1229.0            0.1563            0.38350   

     concavity_worst  concave points_worst  symmetry_worst  \
186          0.35380               0.15710          0.3206   
384          0.28660               0.09173          0.2736   
429          0.03469               0.03612          0.2165   
467          0.06409               0.02500          0.3057   
540          0.17970               0.06918          0.2329   
471          0.05524               0.05547          0.2404   
35           0.54090               0.18130          0.4863   

     fractal_dimension_worst  
186                  0.06938  
384                  0.07320  
429                  0.06025  
467                  0.07875  
540                  0.08134  
471                  0.06639  
35                   0.08633  

[7 rows x 30 columns]

In [17]:
vc.predict(lista_novos_pacientes)

array([1, 0, 0, 0, 0, 0, 1], dtype=int64)

In [18]:
pacientes = pd.DataFrame(['Valentina', 'Rando', 'Ale', 'Ale2', 'Ale3', 'Rando2', 'Enzo'], columns=['Nome'])
pacientes

Nome
0  Valentina
1      Rando
2        Ale
3       Ale2
4       Ale3
5     Rando2
6       Enzo

In [19]:
pacientes['Restultado estimado'] = vc.predict(lista_novos_pacientes)
pacientes

Nome  Restultado estimado
0  Valentina                    1
1      Rando                    0
2        Ale                    0
3       Ale2                    0
4       Ale3                    0
5     Rando2                    0
6       Enzo                    1